# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_personalitymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_persid', models.CharField(max_length=50)),
                ('agegroup_id', models.CharField(max_length=2)),
                ('personality_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agegroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agegroup_id', models.CharField(max_length=50)),
                ('start_age', models.CharField(max_length=2)),
                ('end_age', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Fest_occasmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fest_occasid', models.CharField(max_length=50)),
                ('occas_id', models.CharField(max_length=2)),
                ('fest_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_id', models.CharField(max_length=50)),
                ('personality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_self_rating', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_pwd_reset', models.BooleanField(default=False)),
            ],
        ),
    ]
