# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftsapp', '0002_auto_20170701_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age_personalitymap',
            name='age_persid',
        ),
        migrations.RemoveField(
            model_name='agegroup',
            name='agegroup_id',
        ),
        migrations.RemoveField(
            model_name='fest_occasmap',
            name='fest_occasid',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='personality_id',
        ),
    ]
