# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftsapp', '0003_auto_20170701_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Age_personalitymap',
        ),
        migrations.DeleteModel(
            name='Fest_occasmap',
        ),
    ]
