# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsapp', '0005_auto_20170701_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='imgpath',
            field=models.CharField(max_length=1000),
        ),
    ]
