# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftsapp', '0007_auto_20170703_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='gifts',
            name='cost',
        ),
        migrations.AddField(
            model_name='gift_mapping',
            name='fage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftsapp.Agegroup'),
        ),
        migrations.AddField(
            model_name='gift_mapping',
            name='fpersonality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftsapp.Personality'),
        ),
        migrations.AlterField(
            model_name='gift_mapping',
            name='fgiftsid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gift_mapping',
            name='focassid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftsapp.Occassion'),
        ),
        migrations.AddField(
            model_name='gift_mapping',
            name='fgender',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftsapp.Gender'),
        ),
    ]
