# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsapp', '0009_auto_20170705_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('age', models.CharField(max_length=2)),
                ('personality', models.CharField(max_length=50)),
            ],
        ),
    ]
