# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsapp', '0010_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='cost',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gifts',
            name='giftsid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='imgname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='imgpath',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='qty',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='reviews',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
